# Generated by Django 4.0.5 on 2022-09-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('received_quantity', models.IntegerField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reorder_level', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_csv', models.BooleanField(default=False)),
            ],
        ),
    ]
