# Generated by Django 4.0.5 on 2022-09-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('line_one', models.CharField(blank=True, max_length=255, null=True)),
                ('line_one_quantity', models.IntegerField(blank=True, null=True)),
                ('line_one_unit_price', models.FloatField(blank=True, null=True)),
                ('line_one_total_price', models.FloatField(blank=True, null=True)),
                ('line_two', models.CharField(blank=True, max_length=255, null=True)),
                ('line_two_quantity', models.IntegerField(blank=True, null=True)),
                ('line_two_unit_price', models.FloatField(blank=True, null=True)),
                ('line_two_total_price', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('paid', models.BooleanField(blank=True, default=None, null=True)),
                ('invoice_type', models.CharField(blank=True, choices=[('hr', 'hr'), ('hr', 'hr'), ('hr', 'hr'), ('hr', 'hr'), ('hr', 'hr')], max_length=100, null=True)),
            ],
        ),
    ]
